spring:
  mvc:
    dispatch-options-request: true
  datasource:
    username: chrisdal_csc212
    password: csc212final
    url: jdbc:mysql://208.131.135.17/chrisdal_csc212?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: sa
#    password: sa
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
